version: '2'
services:
    chrome:
        image: robcherry/docker-chromedriver:latest
        environment:
            CHROMEDRIVER_WHITELISTED_IPS: ""

    geckodriver:
        image: quay.io/cvlibrary/geckodriver
        logging:
            driver: none
    httpd:
        image: trinitronx/python-simplehttpserver
        logging:
            driver: none
        volumes:
            - ./xt/www:/var/www
    test:
        build: .
        depends_on:
            - geckodriver
            - httpd
        environment:
            WEBDRIVER_HOST: geckodriver
            WEBDRIVER_CAPABILITIES: '{ "moz:firefoxOptions" : { "args" : ["-headless"] } }'
        volumes:
            - .:/root

    test-chrome:
        build: .
        depends_on:
            - chrome
            - httpd
        environment:
            WEBDRIVER_HOST: chrome
            WEBDRIVER_CAPABILITIES: '{ "chromeOptions" : { "binary" : "/usr/bin/google-chrome", "args": ["--headless"] } }'
        volumes:
            - .:/root

