version: '2'
services:
    geckodriver:
        image: quay.io/cvlibrary/geckodriver:0.28.0
        logging:
            driver: none
    httpd:
        command:
            - -d
            - /var/www
        image: larsks/thttpd
        logging:
            driver: none
        volumes:
            - ./xt/www:/var/www
    test:
        build: .
        depends_on:
            - geckodriver
            - httpd
        volumes:
            - .:/root
