use strict;
use warnings;

use Test::More tests => 58;
use WebDriver::Tiny;

require charnames;

is charnames::vianame('WD_NULL'           ), 57344, 'WD_NULL';
is charnames::vianame('WD_CANCEL'         ), 57345, 'WD_CANCEL';
is charnames::vianame('WD_HELP'           ), 57346, 'WD_HELP';
is charnames::vianame('WD_BACK_SPACE'     ), 57347, 'WD_BACK_SPACE';
is charnames::vianame('WD_TAB'            ), 57348, 'WD_TAB';
is charnames::vianame('WD_CLEAR'          ), 57349, 'WD_CLEAR';
is charnames::vianame('WD_RETURN'         ), 57350, 'WD_RETURN';
is charnames::vianame('WD_ENTER'          ), 57351, 'WD_ENTER';
is charnames::vianame('WD_SHIFT'          ), 57352, 'WD_SHIFT';
is charnames::vianame('WD_CONTROL'        ), 57353, 'WD_CONTROL';
is charnames::vianame('WD_ALT'            ), 57354, 'WD_ALT';
is charnames::vianame('WD_PAUSE'          ), 57355, 'WD_PAUSE';
is charnames::vianame('WD_ESCAPE'         ), 57356, 'WD_ESCAPE';
is charnames::vianame('WD_SPACE'          ), 57357, 'WD_SPACE';
is charnames::vianame('WD_PAGE_UP'        ), 57358, 'WD_PAGE_UP';
is charnames::vianame('WD_PAGE_DOWN'      ), 57359, 'WD_PAGE_DOWN';
is charnames::vianame('WD_END'            ), 57360, 'WD_END';
is charnames::vianame('WD_HOME'           ), 57361, 'WD_HOME';
is charnames::vianame('WD_ARROW_LEFT'     ), 57362, 'WD_ARROW_LEFT';
is charnames::vianame('WD_ARROW_UP'       ), 57363, 'WD_ARROW_UP';
is charnames::vianame('WD_ARROW_RIGHT'    ), 57364, 'WD_ARROW_RIGHT';
is charnames::vianame('WD_ARROW_DOWN'     ), 57365, 'WD_ARROW_DOWN';
is charnames::vianame('WD_INSERT'         ), 57366, 'WD_INSERT';
is charnames::vianame('WD_DELETE'         ), 57367, 'WD_DELETE';
is charnames::vianame('WD_SEMICOLON'      ), 57368, 'WD_SEMICOLON';
is charnames::vianame('WD_EQUALS'         ), 57369, 'WD_EQUALS';
is charnames::vianame('WD_NUMPAD0'        ), 57370, 'WD_NUMPAD0';
is charnames::vianame('WD_NUMPAD1'        ), 57371, 'WD_NUMPAD1';
is charnames::vianame('WD_NUMPAD2'        ), 57372, 'WD_NUMPAD2';
is charnames::vianame('WD_NUMPAD3'        ), 57373, 'WD_NUMPAD3';
is charnames::vianame('WD_NUMPAD4'        ), 57374, 'WD_NUMPAD4';
is charnames::vianame('WD_NUMPAD5'        ), 57375, 'WD_NUMPAD5';
is charnames::vianame('WD_NUMPAD6'        ), 57376, 'WD_NUMPAD6';
is charnames::vianame('WD_NUMPAD7'        ), 57377, 'WD_NUMPAD7';
is charnames::vianame('WD_NUMPAD8'        ), 57378, 'WD_NUMPAD8';
is charnames::vianame('WD_NUMPAD9'        ), 57379, 'WD_NUMPAD9';
is charnames::vianame('WD_MULTIPLY'       ), 57380, 'WD_MULTIPLY';
is charnames::vianame('WD_ADD'            ), 57381, 'WD_ADD';
is charnames::vianame('WD_SEPARATOR'      ), 57382, 'WD_SEPARATOR';
is charnames::vianame('WD_SUBTRACT'       ), 57383, 'WD_SUBTRACT';
is charnames::vianame('WD_DECIMAL'        ), 57384, 'WD_DECIMAL';
is charnames::vianame('WD_DIVIDE'         ), 57385, 'WD_DIVIDE';
is charnames::vianame('WD_F1'             ), 57393, 'WD_F1';
is charnames::vianame('WD_F2'             ), 57394, 'WD_F2';
is charnames::vianame('WD_F3'             ), 57395, 'WD_F3';
is charnames::vianame('WD_F4'             ), 57396, 'WD_F4';
is charnames::vianame('WD_F5'             ), 57397, 'WD_F5';
is charnames::vianame('WD_F6'             ), 57398, 'WD_F6';
is charnames::vianame('WD_F7'             ), 57399, 'WD_F7';
is charnames::vianame('WD_F8'             ), 57400, 'WD_F8';
is charnames::vianame('WD_F9'             ), 57401, 'WD_F9';
is charnames::vianame('WD_F10'            ), 57402, 'WD_F10';
is charnames::vianame('WD_F11'            ), 57403, 'WD_F11';
is charnames::vianame('WD_F12'            ), 57404, 'WD_F12';
is charnames::vianame('WD_META'           ), 57405, 'WD_META';
is charnames::vianame('WD_COMMAND'        ), 57405, 'WD_COMMAND';
is charnames::vianame('WD_ZENKAKU_HANKAKU'), 57408, 'WD_ZENKAKU_HANKAKU';
is charnames::vianame('WD_MADE_UP'        ), undef, 'WD_MADE_UP';
